### ISSUE TITLE
Refactor Regression Tests

### ISSUE THREAD

**Issue by ssvlab** [ssvlab/dsverifier#113]
- Update regression folder for CBMC and ESBMC model checkers
- Add Synthesized Controllers in Closed-Loop and State-Space for CBMC and ESBMC model checkers
- Add script to run all regression tests
- Updat TravisCI script to execute ESBMC and CBMC test cases
- Add CPPLint Checker into TravisCI Script
- Add Scripts to perform CPPLint Checker.
- Add Support for ESBMC 4.4.1 and CBMC 5.7

**Comment by ssvlab** [comment]
@lucasccordeiro @feliperodri

**Comment by lennonchaves** [comment]
Commmit: https://github.com/ssvlab/dsverifier/commit/c8efbaeb5e745f4b174331b37b48c60740fbf6d1
