### ISSUE TITLE
DSVerifier is failing for checking overflow

### ISSUE THREAD

**Issue by lucasccordeiro** [ssvlab/dsverifier#17]
If we run:

dsverifier daes-delta-0-25.c --bmc CBMC --x-size 2 --property OVERFLOW --realization DDFI -DDS_ID=1 -DIMPLEMENTATION_COUNT=1

DSVerifier fails as:

Counterexample:
impl.frac_bits must be less than word width!

impl.int_bits must be less than word width subtracted by precision!

Violated property:
  file ../../bmc/core/initialization.h line 30 function initialization
  assertion 0
  0 != 0

VERIFICATION FAILED

This is the controller:
# if DS_ID == 1

```
digital_system ds = {
    .b = { 0.15, 0.05, 0.4 },
    .b_size = 3,
    .a = { 1.0, 0.0, 0.3 },
    .a_size = 3 
};

#define IMPLEMENTATION_COUNT 1

#if IMPLEMENTATION_ID == 1 

    implementation impl = {
        .int_bits = 3,
        .frac_bits = 4,
        .delta = 0.25,
        .min = -1.0,
        .max = 1.0
    };

#endif 
```
# endif

**Comment by hussamaa** [comment]
Hi,

In order to run this example properly, it is necessary to set the parameter **-DIMPLEMENTATION_ID=1**.

> dsverifier daes-delta-0-25.c --bmc CBMC --x-size 2 --property OVERFLOW --realization DDFI -DDS_ID=1 -DIMPLEMENTATION_ID=1 

Also, the macro "IMPLEMENTATION_COUNT" is used just to guide the benchmarks script.

Thanks,
Hussama Ismail

**Comment by lucasccordeiro** [comment]
We should run as:
dsverifier daes-delta-0-25.c --bmc CBMC --x-size 2 --property OVERFLOW --realization DDFI -DDS_ID=1 -DIMPLEMENTATION_ID=1

Even so, the verification fails (while the DAES paper reports verification successful).

Do you have an update version of the DAES results for your MSc thesis? Or did you just copy the results of the DAES paper?

**Comment by hussamaa** [comment]
Hello,

> Do you have an update version of the DAES results for your MSc thesis? Or did you just copy the results of the DAES paper?

No, I didn't. Actually, the delta implementation was improved (fixed), and new results were produced for the thesis. In addition, for my final report some benchmarks were included, and others were removed, which includes this one.

These benchmarks were used:

[https://github.com/hussamaibrahim/dsverifier/blob/master/benchmarks/msc/Q4/benchmarks-delta-0_25.c](https://github.com/hussamaibrahim/dsverifier/blob/master/benchmarks/msc/Q4/benchmarks-delta-0_25.c)

also, the outcomes are in a spreadsheet, which the link is hereunder:

[https://docs.google.com/spreadsheets/d/1TAwAw66bGe9FbGi7-7J5llklyGZ2GtkzCjT8pCWgzJM/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1TAwAw66bGe9FbGi7-7J5llklyGZ2GtkzCjT8pCWgzJM/edit?usp=sharing)

Thanks,
Hussama Ismail

**Comment by lucasccordeiro** [comment]
Do you have the commit that you used to run these experiments?

Lennon has just fixed some bugs related to the delta operator, but it still fails in all benchmarks related to checking overflow.

Maybe with that commit, Lennon can realize what was the root cause of the problem.

**Comment by hussamaa** [comment]
> Do you have the commit that you used to run these experiments?

Yes, I have. You can use the commit b86587da181ff1af791468a9199faa6fa9bd19fa.

> Lennon has just fixed some bugs related to the delta operator, but it still fails in all benchmarks related to checking overflow.

I see. It is important to keep in mind the difference between the **delta operator implementation** (bmc/core/delta-operator.h), and the **DSVerifier front-end** (dsverifier.cpp). I have realized that the changes were made in the front end, which the cause could be related to a side effect. In addition, at that time, I was not using only the front-end, but was invoking the model checker directly with the correct parameters.

Also, in order to invoke the model checker directly, you can use the command line printed by DSVerifier on the console.

Cheers,
Hussama Ismail
