### ISSUE TITLE
Delta Form verification is not working very well with a benchmark of controllers

### ISSUE THREAD

**Issue by lennonchaves** [ssvlab/dsverifier#2]
If you need use a benchmark file to check and verify many controllers, the DSVerifier is checking only the last controller.

Example of usage:

 ./dsverifier benchmark.c -realization DDFI --property MINIMUM_PHASE --x-size 10 --bmc ESBMC --solver boolector -DDS_ID=1 -DIMPLEMENTATION_ID=1

If benchmark.c has more than one controller (example, 100 controllers), then DSVerifier is checking only the last controller (with DS_ID=100)

**Comment by lucasccordeiro** [comment]
Actually, you have to change the parameters "i" and "j" related to -DDS_ID=i -DIMPLEMENTATION_ID=j, in order to verify a different controller.

Is your idea to pass a .c file with several controllers and then make DSVerifier to verify each one?

**Comment by lennonchaves** [comment]
I apologize for my mistake or If I wasn't clear to report this issue. Actually, it's not about verify a different controller, It's about the ouput generated from verification.

When I'm checking a controller, I'm changing the parameters "i" and "j" to verify a different controller. Then, when you are verifying a controller, the output of verification is printing values of the last controller. The error is about the valued printed in output. Apparently, the verification of controllers using macro parameters is working well.

For example, if you are verifying the minimum phase of the controller 1, the values in output is related to the last controller. If you are verifying the controller 2, 3, 4, 5...100 (and changing in each verification the macro parameters), you'll see that all values in output is related only with the last controller (i.e., the controller with DS_ID=100, in this case).

**Comment by lennonchaves** [comment]
- The bug is related only with Minimum Phase and Stability Properties. Probably, the side-effect is present on this methods.
  check_stability_delta_domain();
  check_minimum_phase_delta_domain();
