### ISSUE TITLE
Check whether the user has provided zero as numerator in the controller TF

### ISSUE THREAD

**Issue by lucasccordeiro** [ssvlab/dsverifier#28]
We must not allow the user user to provide zero as numerator in the controller TF. You can check this via an assertion in the DSVerifier code.

How to reproduce:

$time dsverifier dcmotor_tf_disc1.c --bmc CBMC --property STABILITY_CLOSED_LOOP --connection-mode SERIES

#include <dsverifier.h>

digital_system controller = {
        .b = { 0.0f, 0.0f },
        .b_uncertainty = { 0.0 },
        .b_size = 2,
        .a = { 0.5478515625f, 0.0f },
        .a_uncertainty = { 0.0 },
        .a_size = 2,
        .sample_time = 2,
};

implementation impl = {
        .int_bits = 3,
        .frac_bits = 7,
        .max = 1.0,
        .min = -1.0,
        .scale = 1,
};

digital_system plant = {
        .b = { 0.1898f, 1.8027E-4 },
        .b_uncertainty = { 0.0, 0.0 },
        .b_size = 2,
        .a = { 1.0f, -0.9012f, -1.0006E-16 },
        .a_uncertainty = { 0.0, 0.0, 0.0 },
        .a_size = 3,
};

**Comment by lennonchaves** [comment]
fixed in commit https://github.com/ssvlab/dsverifier/commit/63ce94971053b5d64870cc59997d22129c2899ac
